server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# clients.url → Loki endpoint 요구사항 반영
clients:
  - url: http://loki:3100/loki/api/v1/push

# scrape_configs jobs 1개 이상 요구사항 반영
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          # docker-compose에서 마운트한 VM의 /var/log 디렉토리 로그를 수집
          __path__: /var/log/*log