server:
  http_listen_port: 3200

multitenancy_enabled: false

# 트레이스 데이터를 받아들이는 게이트웨이 설정
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

# 모든 상태 저장 컴포넌트들의 데이터를 지정하는 공통 스토리지 블록
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-data
      endpoint: minio:9000
      access_key: mimir
      secret_key: supersecret
      insecure: true
    # 최신 규격은 블록 관리(ingester/compactor) 설정을 내부 s3 아래에 함께 위임합니다
    wal:
      path: /var/tempo/wal