stream_over_http: true
server:
  http_listen_port: 3200

# 트레이스 데이터를 수신하는 단일 통로 설정
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

# 데이터를 메모리에 임시로 모아두는 버퍼 설정
ingester:
  max_block_duration: 5m

# 실제 트레이스 데이터를 장기 보관할 스토리지 설정 (MinIO)
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-data
      endpoint: minio:9000
      access_key: mimir
      secret_key: supersecret
      insecure: true

# 중복 제거 및 검색 최적화를 위한 컴팩터 설정
compactor:
  compaction:
    block_size: 1h