server:
  http_listen_port: 3200

multitenancy_enabled: false

# 트레이스 데이터를 받아들이는 게이트웨이 설정
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-data
      endpoint: minio:9000
      access_key: mimir
      secret_key: supersecret
      insecure: true
    
    wal:
      path: /var/tempo/wal

    retention:
      block_retention: 24h
      compacted_block_retention: 1h

