apiVersion: 1

datasources:
  # 1. Loki 데이터소스 자동 프로비저닝
  - name: lgtm-loki
    type: loki
    uid: lgtm-loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true

  # 2. Mimir (Prometheus 호환) 데이터소스 자동 프로비저닝
  - name: lgtm-mimir
    type: prometheus
    uid: lgtm-mimir
    access: proxy
    url: http://mimir:9009
    jsonData:
      httpMethod: POST
    isDefault: true
    editable: true

  # 3. Tempo 데이터소스 자동 프로비저닝
  - name: lgtm-tempo
    type: tempo
    uid: lgtm-tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true